In [1]:
import torch
import torch.nn as nn

In [2]:
# We want to create a neuron / tensors
x = [[5, 3, 1, 2], [6, 3, 6, 1]]
x = torch.Tensor(x)

print(x)

tensor([[5., 3., 1., 2.],
        [6., 3., 6., 1.]])


In [3]:
# Class representing your neural network
# 4 (input) --> 3 (hidden layer) --> 2 (hidden layer) --> 1 (output layer)
class SinglePerceptron(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden_layer_1 = nn.Linear(4, 3)
        self.hidden_layer_2 = nn.Linear(3, 2)
        self.output_layer = nn.Linear(2, 1)
        self.activation = nn.Sigmoid()
        
        #self.multiple_hidden_2x2 = nn.Sequential()
        
        #for i in range(1000):
        #    self.multiple_hidden_2x2.append(nn.Linear(2, 2))
        #    self.multiple_hidden_2x2.append(nn.Sigmoid())
    
    def forward(self, x):
        x = self.hidden_layer_1(x)
        x = self.activation(x)
        
        x = self.hidden_layer_2(x)
        x = self.activation(x)
        
        #x = self.multiple_hidden_2x2(x)
        
        y = self.output_layer(x)
        y = self.activation(y)
        
        return y

In [4]:
model = SinglePerceptron()

predictions = model.forward(x)

print(predictions)

tensor([[0.4697],
        [0.4687]], grad_fn=<SigmoidBackward0>)


In [5]:
print(model)

SinglePerceptron(
  (hidden_layer_1): Linear(in_features=4, out_features=3, bias=True)
  (hidden_layer_2): Linear(in_features=3, out_features=2, bias=True)
  (output_layer): Linear(in_features=2, out_features=1, bias=True)
  (activation): Sigmoid()
)


In [6]:
# Loss function
loss_fn = nn.MSELoss()

In [7]:
answer_key = torch.Tensor([[1], [0]])

for i in range(len(predictions)):
    p = predictions[i]
    a = answer_key[i]

    loss = loss_fn(p, a)

    print(loss.item())

0.28121691942214966
0.2196352630853653


In [8]:
# Examine the parameters
num_parameters = 0
for name, param in model.named_parameters():
    print(name)
    print(param.data)
    
    num_parameters += param.numel()

hidden_layer_1.weight
tensor([[-0.4724, -0.4565,  0.0256, -0.2653],
        [ 0.3669, -0.4639, -0.3995, -0.0854],
        [ 0.2321, -0.1159, -0.2555, -0.1545]])
hidden_layer_1.bias
tensor([ 0.0364,  0.3883, -0.0534])
hidden_layer_2.weight
tensor([[ 0.0265, -0.1209, -0.3497],
        [ 0.1799,  0.1489,  0.2416]])
hidden_layer_2.bias
tensor([ 0.4417, -0.3849])
output_layer.weight
tensor([[-0.4121, -0.3001]])
output_layer.bias
tensor([0.2410])


In [9]:
print("Num Parameters: {}".format(num_parameters))

Num Parameters: 26
