In [1]:
import torch
import torch.nn as nn

In [2]:
# We want to create a neuron / tensors
x = [[5, 3, 1, 2], [6, 3, 6, 1]]
x = torch.Tensor(x)

print(x)

tensor([[5., 3., 1., 2.],
        [6., 3., 6., 1.]])


In [3]:
# Class representing your neural network
# 4 (input) --> 3 (hidden layer) --> 2 (hidden layer) --> 1 (output layer)
class SinglePerceptron(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden_layer_1 = nn.Linear(4, 3) # input to first hidden layer
        self.hidden_layer_2 = nn.Linear(3, 2)
        self.output_layer = nn.Linear(2, 1)
        self.activation = nn.Sigmoid()
        
        #self.multiple_hidden_2x2 = nn.Sequential()
        
        #for i in range(1000):
        #    self.multiple_hidden_2x2.append(nn.Linear(2, 2))
        #    self.multiple_hidden_2x2.append(nn.Sigmoid())
    
    def forward(self, x):
        x = self.hidden_layer_1(x)
        x = self.activation(x)
        
        x = self.hidden_layer_2(x)
        x = self.activation(x)
        
        #x = self.multiple_hidden_2x2(x)
        
        y = self.output_layer(x)
        y = self.activation(y)
        
        return y

In [4]:
model = SinglePerceptron()

# predictions = model(x)
predictions = model.forward(x)

print(predictions)

tensor([[0.4716],
        [0.4747]], grad_fn=<SigmoidBackward0>)


In [5]:
print(model)

SinglePerceptron(
  (hidden_layer_1): Linear(in_features=4, out_features=3, bias=True)
  (hidden_layer_2): Linear(in_features=3, out_features=2, bias=True)
  (output_layer): Linear(in_features=2, out_features=1, bias=True)
  (activation): Sigmoid()
)


In [6]:
# Loss function
loss_fn = nn.MSELoss()

In [7]:
answer_key = torch.Tensor([[1], [0]])

for i in range(len(predictions)):
    p = predictions[i]
    a = answer_key[i]

    loss = loss_fn(p, a)

    print(loss.item())

0.2792503535747528
0.22530846297740936


In [8]:
# Examine the parameters
num_parameters = 0
for name, param in model.named_parameters():
    print(name)
    print(param.data)
    
    num_parameters += param.numel()

hidden_layer_1.weight
tensor([[ 0.3903, -0.1565,  0.4396,  0.1145],
        [ 0.3087, -0.4907, -0.1180,  0.1236],
        [ 0.2467,  0.4405, -0.3658, -0.4058]])
hidden_layer_1.bias
tensor([-0.1666, -0.2307, -0.2697])
hidden_layer_2.weight
tensor([[-0.5353, -0.0871,  0.1519],
        [ 0.1610,  0.1941,  0.3033]])
hidden_layer_2.bias
tensor([0.0970, 0.1003])
output_layer.weight
tensor([[-0.4568, -0.1243]])
output_layer.bias
tensor([0.1595])


In [9]:
print("Num Parameters: {}".format(num_parameters))

Num Parameters: 26


In [10]:
# Check the state of the model as a dictionary
print(model.state_dict())

OrderedDict([('hidden_layer_1.weight', tensor([[ 0.3903, -0.1565,  0.4396,  0.1145],
        [ 0.3087, -0.4907, -0.1180,  0.1236],
        [ 0.2467,  0.4405, -0.3658, -0.4058]])), ('hidden_layer_1.bias', tensor([-0.1666, -0.2307, -0.2697])), ('hidden_layer_2.weight', tensor([[-0.5353, -0.0871,  0.1519],
        [ 0.1610,  0.1941,  0.3033]])), ('hidden_layer_2.bias', tensor([0.0970, 0.1003])), ('output_layer.weight', tensor([[-0.4568, -0.1243]])), ('output_layer.bias', tensor([0.1595]))])


In [11]:
# Declare a dictionary that we want to serialize as .pth file
state = { 'state_dict': model.state_dict() }

torch.save(state, "model.pth")

In [12]:
# Load a model
model = SinglePerceptron()

state = torch.load("model.pth")

model.load_state_dict(state['state_dict'])

predictions = model.forward(x)

predictions

tensor([[0.4716],
        [0.4747]], grad_fn=<SigmoidBackward0>)

In [13]:
# Convert a tensor back to a numpy array
preds = predictions.detach().cpu().numpy()

print(preds)

[[0.47155857]
 [0.47466668]]
